name: presensee
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_messaging:
  geolocator:

  tflite_flutter: ^0.11.0
  image_picker: ^1.1.2
  google_mlkit_face_detection: 0.10.0
  image: ^4.2.0


  cupertino_icons: ^1.0.8
 #dev_dependencies:
    #flutter_test:
     #sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/models/mobilefacenet.tflite

 
