org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio1\\jbr
org.gradle.java.home=C:\\Java\\jdk-17.0.18+8


