// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnYAPAkNZIIhCmHPMf_HNb34DxuBrltAU',
    appId: '1:75442217286:web:58ff749de843732653c547',
    messagingSenderId: '75442217286',
    projectId: 'presensee-1989d',
    authDomain: 'presensee-1989d.firebaseapp.com',
    storageBucket: 'presensee-1989d.firebasestorage.app',
    measurementId: 'G-31FD3ZV7MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfRVOBCmtQnkJSaQMlbUYayb_bo_GhLXQ',
    appId: '1:75442217286:android:3bbd1ea1bbcaef4653c547',
    messagingSenderId: '75442217286',
    projectId: 'presensee-1989d',
    storageBucket: 'presensee-1989d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdNjWMCIknWS2V3TRfEHfO5Y-SrpjuD2M',
    appId: '1:75442217286:ios:499ce47d1503069f53c547',
    messagingSenderId: '75442217286',
    projectId: 'presensee-1989d',
    storageBucket: 'presensee-1989d.firebasestorage.app',
    iosClientId: '75442217286-eqpg8q8o3kb5mhc1g172cp3cnq0m16e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.presensee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdNjWMCIknWS2V3TRfEHfO5Y-SrpjuD2M',
    appId: '1:75442217286:ios:499ce47d1503069f53c547',
    messagingSenderId: '75442217286',
    projectId: 'presensee-1989d',
    storageBucket: 'presensee-1989d.firebasestorage.app',
    iosClientId: '75442217286-eqpg8q8o3kb5mhc1g172cp3cnq0m16e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.presensee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnYAPAkNZIIhCmHPMf_HNb34DxuBrltAU',
    appId: '1:75442217286:web:2ef41f6f478668fa53c547',
    messagingSenderId: '75442217286',
    projectId: 'presensee-1989d',
    authDomain: 'presensee-1989d.firebaseapp.com',
    storageBucket: 'presensee-1989d.firebasestorage.app',
    measurementId: 'G-9ZV2N7YW7J',
  );
}
